name = "hrata-telegram-bot"
main = "src/index.js"
compatibility_date = "2024-04-01"

# Cloudflare D1 Database binding
# You will get the database_id after running: npx wrangler d1 create hrata-bot-db
[[d1_databases]]
binding = "hrata_bot_db"
database_name = "hrata-bot-db"
database_id = "7192bd18-27dc-4c39-af51-d8accdfcffd2"